# Generated by Django 5.0.6 on 2024-07-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='courses',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student_details',
            name='degree',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student_details',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student_details',
            name='fee',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student_details',
            name='percetage',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
