# Generated by Django 5.0.6 on 2024-07-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_details_courses_student_details_degree_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details',
            name='percetage',
        ),
        migrations.AddField(
            model_name='student_details',
            name='percentage',
            field=models.FloatField(null=True),
        ),
    ]
