# Generated by Django 5.0.6 on 2024-07-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_student_details_percetage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll_details',
            fields=[
                ('reg_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('fee', models.IntegerField()),
                ('courses', models.CharField(max_length=100)),
                ('percentage', models.FloatField()),
            ],
        ),
    ]
