# Generated by Django 5.0.6 on 2024-07-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_enroll_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll_details',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
