# Generated by Django 5.0.6 on 2024-07-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_enroll_details_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('year_of_passing', models.IntegerField(max_length=4)),
                ('qualification', models.CharField(max_length=100)),
                ('mobile_no', models.IntegerField(max_length=10, unique=True)),
            ],
        ),
    ]
