# Generated by Django 5.0.6 on 2024-07-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_callback'),
    ]

    operations = [
        migrations.AddField(
            model_name='callback',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
