# Generated by Django 5.0.6 on 2024-07-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0008_alter_callback_mobile_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="callback",
            name="mobile_no",
            field=models.IntegerField(verbose_name=10),
        ),
    ]
