# Generated by Django 5.0.6 on 2024-07-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0009_alter_callback_mobile_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="callback",
            name="mobile_no",
            field=models.IntegerField(max_length=10),
        ),
    ]
